Add Dockerfile
Torch is installed separately because a dependency of gfpgan
imports it in its setup.py file. The setup.py file for that package
is evaluated after torch is downloaded but before it's installed,
resulting in a big scary error message:

Collecting basicsr>=1.3.4.0
  Downloading basicsr-1.3.4.9.tar.gz (161 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qs5_vri7/basicsr_04fb0d3a90224774b58ffc0416322372/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qs5_vri7/basicsr_04fb0d3a90224774b58ffc0416322372/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-xrbw3vhh
         cwd: /tmp/pip-install-qs5_vri7/basicsr_04fb0d3a90224774b58ffc0416322372/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-qs5_vri7/basicsr_04fb0d3a90224774b58ffc0416322372/setup.py", line 8, in <module>
        import torch
    ModuleNotFoundError: No module named 'torch'
    ----------------------------------------