Fix crash when uploading a file with multiple dots in name
Fixes this error:
  File "/app/blueprints/endpoints/__init__.py", line 58, in upload_file
    restore_image(os.path.join(UPLOAD_FOLDER, filename))
  File "/app/model.py", line 117, in restore_image
    imwrite(restored_img, save_restore_path)
  File "/usr/local/lib/python3.9/site-packages/basicsr/utils/img_util.py", line 151, in imwrite
    ok = cv2.imwrite(file_path, img, params)
cv2.error: OpenCV(4.5.5) /io/opencv/modules/imgcodecs/src/loadsave.cpp:730: error: (-2:Unspecified error) could not find a writer for the specified extension in function 'imwrite_'

This was caused by splitting from the left instead of from
the right. If the image was named "a.b.c.jpg", the extension
was set to "b" instead of "jpg".

Alternative solution: img_name.rsplit('.', 1)[-1]. str.split
splits from the left (so "a.b.c.jpg".split('.', 1) returns
["a", "b.c.jpg"]), str.rsplit splits from the right (so
"a.b.c.jpg".rsplit('.', 1) returns ["a.b.c", "jpg"]). Same for
os.path.splitext.